layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

social_media:
  facebook: kkrzyzakk
  linkedin: krzyzak

technologies:
  -
    name: Ruby
    icon: devicon-ruby-plain colored
    description:
      I'm a Ruby developer with over 8 years of professional experience.
      I'm an eloquent programmer with a deep knowledge of both standard library and most industry-standard gems.
  -
    name: Ruby on Rails
    icon: devicon-rails-plain colored
    description:
      I enjoy writing maintanable, scalable, well tested code in complex applications.
      I equally like writing both new feautres and refactoring existing ones.
  -
    name: PostgreSQL
    icon: devicon-postgresql-plain colored
    description: 
      I have a knack for solving complex SQL-related issues.
      I can help you with performance optimisations, I can prepare some custom triggers or utilize one of the postgres extensions.
  -
    name: JavaScript
    icon: devicon-javascript-plain colored
    description:
      I'm familiar with modern JS ecosystem.
      I can write ES6+ code or help you with a transition to TypeScript.
  -
    name: ...You name it!
    octicon: beaker
    description:
      I'm always open to new challenges.
  -
    name: React
    icon: devicon-react-plain colored
    description:
      I have experience with React+Redux applications.
      I can create new one from scratch or work on an existing one.

highlights:
  -
    name: Toptal
    description:
      I'm working as a Core Team member, helping with building the largest network of the top freelance talents
    image_url: assets/toptal.png
    web_url: https://toptal.com
    technologies:
      -
        name: ruby
        icon: ruby-plain
        description:
          Working on large applications with hundreds of thousands of lines of code
      -
        name: postgres
        icon: postgresql-plain
        description:
          Writing zero downtime migrations, optimizing queries, performing complex tree-based queries
  -
    name: Estetio
    description:
      I implemented a modern application for managing beauty/hair salons.
      This application uses a lot of cutting-edge technologies, including React+Redux, Typescript,
      and a backend application written in Rails
    image_url: assets/estetio.svg
    web_url: https://estetio.pl
    technologies:
      -
        name: react
        icon: react-plain
        description: Modern React+Redux application utilizing a lot of the cutting-edge technologies.
      -
        name: rails
        icon: rails-plain
        description: API-only application serving JSON data to the frontend app.
  -
    name: Lonely Planet
    description:
      I was working on a project that was focused on processing data coming from various partner APIs.
      Task included aggregating, sanitizing and normalizing data from extremely diverse sources
    image_url: assets/lp.png
    web_url: https://lonelyplanet.com
    technologies:
      -
        name: ruby
        icon: ruby-plain
        description: Non-rails application with a lot of performance optimizations
      -
        name: postgres
        icon: postgresql-plain
        description: Writing complex, performant queries, including some that have been using geospatial data (with postGIS extension)

repositories:
  -
    name: 'chaps-io/gush'
    language: Ruby
    description:
      Fast and distributed workflow runner using ActiveJob and Redis.
      Featured in RubyWeekly.
  -
    name: 'chaps-io/gush-control'
    language: CoffeeScript
    description:
      Web GUI for monitoring and managing Gush workflows.
  -
    name: 'aftership/aftership-sdk-ruby'
    language: Ruby
    description:
      Official SDK for Aftership app.
  -
    name: 'postmen/postmen-sdk-ruby'
    language: Ruby
    description:
      Official SDK for Postmen app.
  -
    name: 'hanami/controller'
    language: Ruby
    description:
      Controller layer for the Hanami web framework.
  -
    name: 'plataformatec/simple_form'
    language: Ruby
    description:
      One of the most popular gems that provides DSL for building forms in Rails.