layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 6
  exclude:
    forks: false
    projects:
    - personal-website
    - phony
    - webmock
    - readability

social_media:
  facebook: kkrzyzakk
  linkedin: krzyzak

technologies:
  -
    name: Ruby
    icon: ruby-plain colored
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/ruby/ruby.png
  -
    name: Ruby on Rails
    icon: rails-plain colored
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/rails/rails.png
  -
    name: PostgreSQL
    icon: postgresql-plain colored
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/postgresql/postgresql.png
  -
    name: JavaScript
    icon: javascript-plain colored
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png
  -
    name: spacer
  -
    name: React
    icon: react-plain colored
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

highlights:
  -
    name: Toptal
    description:
      I'm working as a Core Team member, helping with building the largest network of the top freelance talents
    image_url: assets/toptal.png
    web_url: https://toptal.com
    technologies:
      -
        name: ruby
        icon: ruby-plain
        description:
          Working on large applications with hundreds of thousands of lines of code
      -
        name: postgres
        icon: postgresql-plain
        description:
          Writing zero downtime migrations, optimizing queries, performing complex tree-based queries
  -
    name: Estetio
    description:
      I implemented a modern application for managing a beauty/hair salons.
      This application uses a lot of cutting-edge technologies, including React+Redux, Typescript,
      and a backend application written in Rails
    image_url: assets/estetio.svg
    web_url: https://estetio.pl
    technologies:
      -
        name: react
        icon: react-plain
        description: Modern React+Redux application utilizing a lot of the cutting-edge technologies.
      -
        name: rails
        icon: rails-plain
        description: API-only application serving JSON data to the frontend app.
  -
    name: Lonely Planet
    description:
      I was working on a project that was focused on processing data coming from various partner APIs.
      Task included aggregating, sanitizing and normalizing data from extremely diverse sources
    image_url: assets/lp.png
    web_url: https://lonelyplanet.com
    technologies:
      -
        name: ruby
        icon: ruby-plain
        description: Non-rails application with a lot of performance optimizations
      -
        name: postgres
        icon: postgresql-plain
        description: Writing complex, performant queries, including some that have been using geospatial data (with postGIS extension)
